from connect_db import get_connection 
import random 

# Cameras in 40 x 40 km of area (DELHI)
LAT_BOUNDS = (28.4000 , 28.8000)
LONG_BOUNDS = (77.0000 , 77.4000)

LOCATIONS = [
    "Connaught Place",
    "Chandni Chowk",
    "India Gate",
    "Lajpat Nagar",
    "Karol Bagh",
    "Hauz Khas",
    "Saket",
    "Vasant Kunj",
    "Dwarka",
    "Rohini",
    "Pitampura",
    "Janakpuri",
    "Rajouri Garden",
    "Nehru Place",
    "Okhla",
    "Greater Kailash",
    "Dhaula Kuan",
    "Aerocity",
    "Chanakyapuri",
    "Paharganj"
]

def setup_infrastruct( chunk = 1000):

    with get_connection() as db:
        with db.cursor() as cursor:

            # Making sure table exists 
            cursor.execute("""CREATE TABLE IF NOT EXISTS cameras(
                           camera_id VARCHAR(20) PRIMARY KEY,
                           location_name VARCHAR(100),
                           latitude DECIMAL (9,6),
                           longitude DECIMAL (9,6)
                           )
                           """)
            
            #Taking the maximum of number part (0000) of camera ids (CAM-0000) by taking the no. part of ids (0000) and cast them into int from strings
            cursor.execute("SELECT MAX(CAST(SUBSTRING(camera_id,5) AS UNSIGNED)) FROM cameras")

            #Taking the first element of first row generated by fetchone() in form of (A,)
            result = cursor.fetchone()[0]

            # Dynamically calculate first and last no. for camera ids 
            # If / Else in ternary way (SYNTAX = value_if_true  if[condition] else value_if _false )
            first_num = (result if result else 0)+1
            last_num = first_num + chunk 
            print(f"INFRASTRUCTURE : ADDING cameras {first_num} to {last_num-1} ")
            
            camera_list = []
            for i in range(first_num , last_num):

                #Generating the ids in form of CAM-0000
                #:04d is a special instruction which means: formatting this in decimal int ,make it 4 characters wide and fill any empty space with 0s.
                cam_id = f"CAM-{i:04d}"

                # '*' is a unpacking function which helps in passing the tuple values 
                lat = round(random.uniform(*LAT_BOUNDS),6)
                long = round(random.uniform(*LONG_BOUNDS),6)
                loc_name = random.choice(LOCATIONS)
                camera_list.append((cam_id,loc_name,lat,long))

            # %s is used as a 'placeholder' which prevents SQL injection attacks.
            # Use to store anything that inserted as the data and db engine strictly treat it as data not code and also handles formatting.
            query = """INSERT INTO cameras(camera_id,location_name,latitude,longitude) VALUES (%s,%s,%s,%s)"""
            cursor.executemany(query,camera_list)

            db.commit()

            print(f"SUCCESS----{chunk} new cameras registered")
         
if __name__ == "__main__":
    setup_infrastruct()